# 1. Первичный анализ данных

### **Data Science проект:**
1. Постановка задачи
2. Получение данных
3. Анализ данных
4. Визуализация данных
5. Предобработка данных
6. Генерация новых признаков
7. Построение модели
8. Оценка качества
9. Внедрение модели
10. Мониторинг качества и улучшение модели

**Подключение библиотек и скриптов**

In [1]:
import numpy as np
import pandas as pd

from scipy.stats import mode

import zipfile

**Где найти файл**

https://drive.google.com/file/d/1RJk-fL5hRd6EBIkY5miVmwGx5IKyo7xn/view?usp=sharing

In [2]:
!gdown 1CW0EA4MvkWENRjDfUcCgQWAa1yx1Sc8s -O housing.сsv

Downloading...
From: https://drive.google.com/uc?id=1CW0EA4MvkWENRjDfUcCgQWAa1yx1Sc8s
To: D:\MyJupyterNotebook\Обучение\GitHub\01_data_analysis\housing.сsv

  0%|          | 0.00/39.5k [00:00<?, ?B/s]
100%|##########| 39.5k/39.5k [00:00<00:00, 633kB/s]

In [3]:
DATASET_PATH = './housing.csv'
PREPARED_DATASET_PATH = './housing_prepared.csv'

### 1. Загрузка данных <a class='anchor' id='load'>

**Описание задачи**

Цель - предсказать стоимость дома

**Описание датасета**

Статистические данные о ряде домов в Калифорнии, основанные на переписи 1990 года.

* **longitude** - долгота
* **latitude** - широта
* **housing_median_age** - средний возраст дома
* **total_rooms** - общее количество комнат
* **total_bedrooms** - общее количество спален
* **population** - количество проживающих
* **households** - домохозяйства
* **ocean_proximity** - близость океана
* **median_income** - средний доход
* **median_house_value** - средняя стоимость дома

In [4]:
df = pd.read_csv(DATASET_PATH, sep=',')
df.head(2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,1

In [5]:
df.tail(2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND,20638
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND,20639

In [6]:
df.sample(5) #получаем случайную долю объектов

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id
14539,-117.14,32.92,15.0,1558.0,314.0,949.0,332.0,5.2864,174400.0,<1H OCEAN,14539
2761,-116.05,33.33,17.0,290.0,94.0,135.0,57.0,1.7292,81300.0,INLAND,2761
9068,-118.15,34.71,36.0,1338.0,250.0,709.0,250.0,3.5625,101400.0,INLAND,9068
14010,-117.19,32.76,52.0,1294.0,175.0,434.0,180.0,5.7914,500001.0,NEAR OCEAN,14010
1912,-120.16,39.01,16.0,1463.0,264.0,54.0,26.0,4.9750,206300.0,INLAND,1912

С помощью .sample можно получить случайную долю объектов, либо перемешать весь датасет

In [7]:
df.sample(frac=1) # перемешиваем датасет

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id
7586,-118.23,33.90,31.0,2143.0,522.0,2276.0,519.0,1.8095,100800.0,<1H OCEAN,7586
3555,-118.59,34.23,17.0,6592.0,1525.0,4459.0,1463.0,3.0347,254500.0,<1H OCEAN,3555
18761,-122.23,40.63,16.0,1141.0,220.0,563.0,200.0,2.3287,130700.0,INLAND,18761
19742,-122.72,40.17,16.0,396.0,78.0,188.0,72.0,1.3889,87500.0,INLAND,19742
3316,-122.69,38.94,9.0,1245.0,234.0,517.0,187.0,3.1250,93400.0,INLAND,3316
...,...,...,...,...,...,...,...,...,...,...,...
13485,-117.37,34.13,18.0,5877.0,1043.0,3114.0,1002.0,4.0294,133200.0,INLAND,13485
16075,-122.48,37.74,NaN,2285.0,435.0,1211.0,442.0,4.0208,323100.0,NEAR OCEAN,16075
4038,-118.51,34.16,23.0,11154.0,1995.0,4076.0,1809.0,5.4609,500001.0,<1H OCEAN,4038
10409,-117.59,33.66,NaN,1318.0,218.0,673.0,225.0,6.0722,260800.0,<1H OCEAN,10409
16943,-122.31,37.55,52.0,900.0,183.0,371.0,166.0,3.2500,296400.0,NEAR OCEAN,16943

In [8]:
df.shape

(20640, 11)

In [9]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity', 'id'],
      dtype='object')

In [10]:
df.index

RangeIndex(start=0, stop=20640, step=1)

In [11]:
df['total_rooms']

0         880.0
1        7099.0
2        1467.0
3        1274.0
4        1627.0
          ...
20635    1665.0
20636     697.0
20637    2254.0
20638    1860.0
20639    2785.0
Name: total_rooms, Length: 20640, dtype: float64

In [12]:
df.total_rooms

0         880.0
1        7099.0
2        1467.0
3        1274.0
4        1627.0
          ...
20635    1665.0
20636     697.0
20637    2254.0
20638    1860.0
20639    2785.0
Name: total_rooms, Length: 20640, dtype: float64

In [13]:
df[['total_rooms', 'total_bedrooms']]

       total_rooms  total_bedrooms
0            880.0           129.0
1           7099.0          1106.0
2           1467.0           190.0
3           1274.0           235.0
4           1627.0           280.0
...            ...             ...
20635       1665.0           374.0
20636        697.0           150.0
20637       2254.0           485.0
20638       1860.0           409.0
20639       2785.0           616.0

[20640 rows x 2 columns]

## Фильтрация

In [14]:
df['population'] > 400

0        False
1         True
2         True
3         True
4         True
         ...
20635     True
20636    False
20637    False
20638     True
20639     True
Name: population, Length: 20640, dtype: bool

In [15]:
df[df['population'] > 400].head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,1
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,2
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,3
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,4
5,-122.25,37.85,52.0,919.0,213.0,413.0,193.0,4.0368,269700.0,NEAR BAY,5

In [16]:
df[(df['population'] > 100) & (df['households'] > 100)].head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,1
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,2
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,3
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,4

In [17]:
df[(df['population'] > 100) | (df['households'] > 100)].head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,1
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,2
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,3
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,4

In [18]:
~(df['population'] > 100)

0        False
1        False
2        False
3        False
4        False
         ...
20635    False
20636    False
20637     True
20638    False
20639    False
Name: population, Length: 20640, dtype: bool

In [19]:
df[~(df['population'] > 100)].head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id
34,-122.27,37.83,51.0,2665.0,574.0,NaN,536.0,2.7303,109700.0,NEAR BAY,34
59,-122.29,37.82,2.0,158.0,43.0,94.0,57.0,2.5625,60000.0,NEAR BAY,59
61,-122.29,37.82,49.0,135.0,29.0,86.0,23.0,6.1183,75000.0,NEAR BAY,61
73,-122.29,37.81,46.0,12.0,4.0,18.0,7.0,0.4999,67500.0,NEAR BAY,73
121,-122.24,37.85,37.0,334.0,54.0,98.0,47.0,4.9643,335000.0,NEAR BAY,121

## Индексация

In [20]:
tmp = df[~(df['population'] > 100)]
tmp.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id
34,-122.27,37.83,51.0,2665.0,574.0,NaN,536.0,2.7303,109700.0,NEAR BAY,34
59,-122.29,37.82,2.0,158.0,43.0,94.0,57.0,2.5625,60000.0,NEAR BAY,59
61,-122.29,37.82,49.0,135.0,29.0,86.0,23.0,6.1183,75000.0,NEAR BAY,61
73,-122.29,37.81,46.0,12.0,4.0,18.0,7.0,0.4999,67500.0,NEAR BAY,73
121,-122.24,37.85,37.0,334.0,54.0,98.0,47.0,4.9643,335000.0,NEAR BAY,121

In [21]:
tmp.index

Index([   34,    59,    61,    73,   121,   129,   140,   167,   194,   201,
       ...
       20452, 20453, 20484, 20489, 20502, 20571, 20624, 20625, 20633, 20637],
      dtype='int64', length=828)

Взятие наблюдения по индексу

In [22]:
tmp.loc[[34, 59], ['longitude', 'latitude']]

    longitude  latitude
34    -122.27     37.83
59    -122.29     37.82

In [23]:
tmp.iloc[[0, 1, 2], [0, 1]]

    longitude  latitude
34    -122.27     37.83
59    -122.29     37.82
61    -122.29     37.82

In [24]:
tmp.loc[:61]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id
34,-122.27,37.83,51.0,2665.0,574.0,NaN,536.0,2.7303,109700.0,NEAR BAY,34
59,-122.29,37.82,2.0,158.0,43.0,94.0,57.0,2.5625,60000.0,NEAR BAY,59
61,-122.29,37.82,49.0,135.0,29.0,86.0,23.0,6.1183,75000.0,NEAR BAY,61

In [25]:
tmp.iloc[:5]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id
34,-122.27,37.83,51.0,2665.0,574.0,NaN,536.0,2.7303,109700.0,NEAR BAY,34
59,-122.29,37.82,2.0,158.0,43.0,94.0,57.0,2.5625,60000.0,NEAR BAY,59
61,-122.29,37.82,49.0,135.0,29.0,86.0,23.0,6.1183,75000.0,NEAR BAY,61
73,-122.29,37.81,46.0,12.0,4.0,18.0,7.0,0.4999,67500.0,NEAR BAY,73
121,-122.24,37.85,37.0,334.0,54.0,98.0,47.0,4.9643,335000.0,NEAR BAY,121

In [26]:
tmp.iloc[-6:-1]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id
20502,-118.68,34.33,45.0,121.0,25.0,67.0,27.0,2.9821,325000.0,<1H OCEAN,20502
20571,-121.99,38.53,6.0,4598.0,834.0,NaN,812.0,3.4186,127300.0,INLAND,20571
20624,-121.41,39.04,16.0,1698.0,300.0,NaN,291.0,3.0739,87200.0,INLAND,20624
20625,-121.52,39.12,37.0,102.0,17.0,29.0,14.0,4.1250,72000.0,INLAND,20625
20633,-121.53,39.19,27.0,2080.0,412.0,NaN,382.0,2.5495,98300.0,INLAND,20633

## Добавление данных

In [27]:
df['NEAR BAY'] = 0
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id,NEAR BAY
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,0,0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,1,0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,2,0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,3,0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,4,0

In [28]:
df['ocean_proximity'] == 'NEAR BAY'

0         True
1         True
2         True
3         True
4         True
         ...
20635    False
20636    False
20637    False
20638    False
20639    False
Name: ocean_proximity, Length: 20640, dtype: bool

In [29]:
df[df['ocean_proximity'] == 'NEAR BAY']['NEAR BAY'] = 1

C:\Users\misha\AppData\Local\Temp\ipykernel_29292\1528906394.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df['ocean_proximity'] == 'NEAR BAY']['NEAR BAY'] = 1

In [30]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id,NEAR BAY
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,0,0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,1,0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,2,0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,3,0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,4,0

In [31]:
df.loc[df['ocean_proximity'] == 'NEAR BAY', 'NEAR BAY'] = 1
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id,NEAR BAY
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,0,1
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,1,1
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,2,1
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,3,1
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,4,1

In [32]:
for i, row in df.iterrows():
    print(i, row)
    break

0 longitude              -122.23
latitude                 37.88
housing_median_age        41.0
total_rooms              880.0
total_bedrooms           129.0
population               322.0
households               126.0
median_income           8.3252
median_house_value    452600.0
ocean_proximity       NEAR BAY
id                           0
NEAR BAY                     1
Name: 0, dtype: object

In [33]:
new_feature = []

for i, row in df.iterrows():
    if row.ocean_proximity == 'INLAND':
        new_feature.append(1)
    else:
        new_feature.append(0)

df['INLAND'] = new_feature
df.sample(5)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id,NEAR BAY,INLAND
15908,-122.42,37.74,52.0,1916.0,432.0,889.0,424.0,4.0391,279900.0,NEAR BAY,15908,1,0
12233,-116.95,33.74,20.0,2233.0,431.0,1024.0,399.0,2.4554,89400.0,INLAND,12233,0,1
20258,-119.17,34.20,36.0,2028.0,523.0,2751.0,496.0,3.0150,149300.0,NEAR OCEAN,20258,0,0
10357,-117.66,33.59,18.0,4552.0,706.0,1918.0,671.0,7.5791,288100.0,<1H OCEAN,10357,0,0
9226,-120.04,36.93,11.0,3606.0,699.0,2074.0,644.0,2.6941,63300.0,INLAND,9226,0,1

## Удаление

In [34]:
df.drop('INLAND', axis=1)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id,NEAR BAY
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,0,1
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,1,1
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,2,1
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,3,1
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND,20635,0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND,20636,0
20637,-121.22,39.43,17.0,2254.0,485.0,NaN,433.0,1.7000,92300.0,INLAND,20637,0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND,20638,0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND,20639,0

In [35]:
df.drop(columns='INLAND')

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id,NEAR BAY
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,0,1
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,1,1
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,2,1
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,3,1
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND,20635,0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND,20636,0
20637,-121.22,39.43,17.0,2254.0,485.0,NaN,433.0,1.7000,92300.0,INLAND,20637,0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND,20638,0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND,20639,0

In [36]:
df.drop(columns='INLAND', inplace=True)
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id,NEAR BAY
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,0,1
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,1,1
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,2,1
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,3,1
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,4,1

## Первичный анализ данных

In [37]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
id                      int64
NEAR BAY                int64
dtype: object

In [38]:
type(df.longitude)

pandas.core.series.Series

In [39]:
df['id'].dtype

dtype('int64')

In [40]:
df['id']

0            0
1            1
2            2
3            3
4            4
         ...
20635    20635
20636    20636
20637    20637
20638    20638
20639    20639
Name: id, Length: 20640, dtype: int64

In [41]:
df['id'].values

array([    0,     1,     2, ..., 20637, 20638, 20639], dtype=int64)

In [42]:
type(df['id'].values)

numpy.ndarray

In [43]:
df['id'] = df['id'].astype(str)
df['id'].dtype

dtype('O')

### Обзор количественных переменных

*Количественные (непрерывные) переменные*  - это переменные, которые могут принимать любые числовые значения в некотором диапазоне.

In [44]:
df_num_features = df.select_dtypes(include=['float64', 'int64'])
df_num_features.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,NEAR BAY
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,1
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,1
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,1
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,1
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,1

С помощью .describe можно получить первичное понимание того, что из себя представляют данные

In [45]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,NEAR BAY
count,20640.000000,20640.000000,19918.000000,20640.000000,20433.000000,20041.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.471242,35.036934,28.653630,2635.763081,537.870553,1425.418243,499.539680,3.870671,206855.816909,0.110853
std,5.041408,94.903955,12.576796,2181.615252,421.385070,1135.185798,382.329753,1.899822,115395.615874,0.313957
min,-124.350000,-13534.030000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000,0.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,786.000000,280.000000,2.563400,119600.000000,0.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1165.000000,409.000000,3.534800,179700.000000,0.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1726.000000,605.000000,4.743250,264725.000000,0.000000
max,122.030000,1327.130000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000,1.000000

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  19918 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20041 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
 10  id                  20640 non-null  object
 11  NEAR BAY            20640 non-null  int64
dtypes: float64(9), int64(1), object(2)
memory usage: 1.9+ MB

#### Статистика

In [47]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

**Среднее арифметическое**

In [48]:
mean = a.sum() / len(a)
mean

3.0

**Дисперсия и стандартное отклонение**

*Дисперсия* - это показатель вариации, который представляет собой средний квадрат отклонений от математического ожидания (среднее арифметическое). Она выражает разброс чисел относительно среднего значения.

*Стандартное отклонение* (среднеквадратичное отклонение) - это величина, характеризующая разброс данных относительно среднего значения.

In [49]:
a - mean

array([-2., -1.,  0.,  1.,  2.])

$$var = \frac{1}{n}\sum(x - x_m)^2$$

In [50]:
variance = np.mean((a - mean) ** 2)
std = np.sqrt(variance)
variance, std

(2.0, 1.4142135623730951)

Подсчет с помощью numpy

In [51]:
mean_np = np.mean(a)
mean_np

3.0

In [52]:
std_np = np.std(a)
std_np

1.4142135623730951

In [53]:
np.var(a)

2.0

**Min, Max**

In [54]:
np.min(a), np.max(a)

(1, 5)

**Медиана**

*Медиана* - значение, которая делит его на две равные части или же проще говоря, это середина отсортированной выборки.

In [55]:
a = [3, 4, 5, 6, 1, 2, 2, 6]
a = np.sort(a)
a

array([1, 2, 2, 3, 4, 5, 6, 6])

In [56]:
len(a)

8

In [57]:
np.median(a)

3.5

**Квантили**

*Квартили* - это значения, которые делят выборку на 4 равные (по количеству объектов) части.
Откуда следует, что вторая квартиль - это медиана.

In [58]:
np.quantile(a, 0.5)

3.5

In [59]:
np.median(a)

3.5

In [60]:
np.quantile(a, q=0.25)

2.0

In [61]:
np.quantile(a, q=0.75)

5.25

**Мода**

Мода - это объект с максимальной частотой или проще говоря, самый популярный (частовстречаемый) объект в выборке.

In [62]:
a

array([1, 2, 2, 3, 4, 5, 6, 6])

In [63]:
mode(a)

ModeResult(mode=2, count=2)

In [64]:
pd.Series(a).mode()

0    2
1    6
dtype: int32

Применим статистику к нашим данным

In [65]:
np.quantile(df['total_rooms'], q=0.5)

2127.0

In [66]:
df['total_rooms'].median()

2127.0

In [67]:
np.quantile(df['total_rooms'], q=0.25)

1447.75

In [68]:
df['total_rooms'].describe()

count    20640.000000
mean      2635.763081
std       2181.615252
min          2.000000
25%       1447.750000
50%       2127.000000
75%       3148.000000
max      39320.000000
Name: total_rooms, dtype: float64

In [69]:
df['total_rooms'].mode()

0    1527.0
Name: total_rooms, dtype: float64

In [70]:
df['total_rooms'].value_counts()

total_rooms
1527.0     18
1613.0     17
1582.0     17
2127.0     16
1717.0     15
           ..
9614.0      1
10839.0     1
11872.0     1
6205.0      1
10035.0     1
Name: count, Length: 5926, dtype: int64

In [71]:
df[df['total_rooms'] == 1527].shape

(18, 12)

### Обзор номинативных переменных
    
*Номинативная (категориальная) переменная* - качественная (неколичественная) переменная величина

In [72]:
df_obj_features = df.select_dtypes(include='object')
df_obj_features.head()

  ocean_proximity id
0        NEAR BAY  0
1        NEAR BAY  1
2        NEAR BAY  2
3        NEAR BAY  3
4        NEAR BAY  4

In [73]:
df['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     9127
INLAND        6542
NEAR OCEAN    2655
NEAR BAY      2288
-               23
ISLAND           5
Name: count, dtype: int64

In [74]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', '-', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [75]:
df['ocean_proximity'].nunique()

6

## Сортировка данных

In [76]:
df.sort_values('median_house_value').head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id,NEAR BAY
9188,-117.86,34.24,52.0,803.0,267.0,628.0,225.0,4.1932,14999.0,INLAND,9188,0
19802,-123.17,40.31,36.0,98.0,28.0,18.0,8.0,0.5360,14999.0,INLAND,19802,0
2799,-117.02,36.40,19.0,619.0,239.0,490.0,164.0,2.1000,14999.0,INLAND,2799,0
2521,-122.74,39.71,16.0,255.0,73.0,85.0,38.0,1.6607,14999.0,INLAND,2521,0
5887,-118.33,34.15,39.0,493.0,168.0,259.0,138.0,2.3667,17500.0,<1H OCEAN,5887,0

In [77]:
df.sort_values('median_house_value', ascending=False).head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id,NEAR BAY
10667,-117.88,33.55,27.0,2278.0,316.0,772.0,304.0,10.1275,500001.0,<1H OCEAN,10667,0
16916,-122.34,37.57,52.0,2635.0,408.0,967.0,374.0,7.0422,500001.0,NEAR OCEAN,16916,0
16946,-122.33,37.55,33.0,2199.0,312.0,827.0,319.0,6.1349,500001.0,NEAR OCEAN,16946,0
8877,-118.49,34.04,48.0,2381.0,345.0,859.0,306.0,8.0257,500001.0,<1H OCEAN,8877,0
8878,-118.50,34.04,52.0,3000.0,374.0,1143.0,375.0,15.0001,500001.0,<1H OCEAN,8878,0

In [78]:
df.sort_values(['housing_median_age', 'total_rooms']).head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,id,NEAR BAY
12286,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.6250,55000.0,INLAND,12286,0
3130,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.8750,141700.0,INLAND,3130,0
18972,-122.00,38.23,1.0,2062.0,343.0,872.0,268.0,5.2636,191300.0,INLAND,18972,0
19536,-120.93,37.65,1.0,2254.0,328.0,402.0,112.0,4.2500,189200.0,INLAND,19536,0
2774,-115.80,33.26,2.0,96.0,18.0,30.0,16.0,5.3374,47500.0,INLAND,2774,0

## Объединение таблиц

Ссылка на google drive: https://drive.google.com/file/d/1CW0EA4MvkWENRjDfUcCgQWAa1yx1Sc8s/view?usp=sharing

In [79]:
!gdown 1CW0EA4MvkWENRjDfUcCgQWAa1yx1Sc8s -O data.zip

Downloading...
From: https://drive.google.com/uc?id=1CW0EA4MvkWENRjDfUcCgQWAa1yx1Sc8s
To: D:\MyJupyterNotebook\Обучение\GitHub\01_data_analysis\data.zip

  0%|          | 0.00/39.5k [00:00<?, ?B/s]
100%|##########| 39.5k/39.5k [00:00<00:00, 816kB/s]

In [80]:
with zipfile.ZipFile("data.zip", "r") as zip_ref:
    zip_ref.extractall()

In [81]:
df = pd.read_csv('advertising.csv')

df['User_id'] = pd.Series(range(1000, 2000))

df.head()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad,User_id
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,2016-03-27 00:53:11,0,1000
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,2016-04-04 01:39:02,0,1001
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,2016-03-13 20:35:42,0,1002
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,2016-01-10 02:31:19,0,1003
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,2016-06-03 03:36:18,0,1004

In [82]:
cols_1 = ['User_id', 'Daily Time Spent on Site', 'Ad Topic Line', 'Timestamp', 'Clicked on Ad']
df_site = df[cols_1]

print('Размер датасета df_site:', df_site.shape)
df_site.head()

Размер датасета df_site: (1000, 5)

,User_id,Daily Time Spent on Site,Ad Topic Line,Timestamp,Clicked on Ad
0,1000,68.95,Cloned 5thgeneration orchestration,2016-03-27 00:53:11,0
1,1001,80.23,Monitored national standardization,2016-04-04 01:39:02,0
2,1002,69.47,Organic bottom-line service-desk,2016-03-13 20:35:42,0
3,1003,74.15,Triple-buffered reciprocal time-frame,2016-01-10 02:31:19,0
4,1004,68.37,Robust logistical utilization,2016-06-03 03:36:18,0

In [83]:
cols_2 = ['User_id', 'Male', 'Age', 'Country', 'City', 'Daily Internet Usage']
df_personal = df[cols_2]

print('Размер датасета df_personal:', df_personal.shape)
df_personal.head()

Размер датасета df_personal: (1000, 6)

   User_id  Male  Age     Country            City  Daily Internet Usage
0     1000     0   35     Tunisia     Wrightburgh                256.09
1     1001     1   31       Nauru       West Jodi                193.77
2     1002     0   26  San Marino        Davidton                236.50
3     1003     1   29       Italy  West Terrifurt                245.89
4     1004     0   35     Iceland    South Manuel                225.58

In [84]:
cols_3 = ['Country', 'City', 'Area Income']

df_macro = df[cols_3][:-50]

print('Размер датасета df_macro:', df_macro.shape)
df_macro.head()

Размер датасета df_macro: (950, 3)

      Country            City  Area Income
0     Tunisia     Wrightburgh     61833.90
1       Nauru       West Jodi     68441.85
2  San Marino        Davidton     59785.94
3       Italy  West Terrifurt     54806.18
4     Iceland    South Manuel     73889.99

### merge

<img src='https://absentdata.com/wp-content/uploads/2019/07/pd.merge-1.png'>

<img src='https://www.thecrazyprogrammer.com/wp-content/uploads/2019/05/Joins-in-SQL-Inner-Outer-Left-and-Right-Join.jpg?ezimgfmt=rs:372x290/rscb1/ngcb1/notWebP'>

In [85]:
# Предположим, что мы получили эти три датасета из разных источников и теперь нам нужно их объединить

df_2 = pd.merge(df_site, df_personal, on='User_id', how='inner')

print('Размер датасета df_2:', df_2.shape)
df_2.head()

Размер датасета df_2: (1000, 10)

,User_id,Daily Time Spent on Site,Ad Topic Line,Timestamp,Clicked on Ad,Male,Age,Country,City,Daily Internet Usage
0,1000,68.95,Cloned 5thgeneration orchestration,2016-03-27 00:53:11,0,0,35,Tunisia,Wrightburgh,256.09
1,1001,80.23,Monitored national standardization,2016-04-04 01:39:02,0,1,31,Nauru,West Jodi,193.77
2,1002,69.47,Organic bottom-line service-desk,2016-03-13 20:35:42,0,0,26,San Marino,Davidton,236.50
3,1003,74.15,Triple-buffered reciprocal time-frame,2016-01-10 02:31:19,0,1,29,Italy,West Terrifurt,245.89
4,1004,68.37,Robust logistical utilization,2016-06-03 03:36:18,0,0,35,Iceland,South Manuel,225.58

In [86]:
df_macro.shape

(950, 3)

In [87]:
df_3 = df_2.merge(df_macro, left_on=['Country', 'City'], right_on=['Country', 'City'], how='left')

print('Размер датасета df_3:', df_3.shape)
df_3.head()

Размер датасета df_3: (1000, 11)

,User_id,Daily Time Spent on Site,Ad Topic Line,Timestamp,Clicked on Ad,Male,Age,Country,City,Daily Internet Usage,Area Income
0,1000,68.95,Cloned 5thgeneration orchestration,2016-03-27 00:53:11,0,0,35,Tunisia,Wrightburgh,256.09,61833.90
1,1001,80.23,Monitored national standardization,2016-04-04 01:39:02,0,1,31,Nauru,West Jodi,193.77,68441.85
2,1002,69.47,Organic bottom-line service-desk,2016-03-13 20:35:42,0,0,26,San Marino,Davidton,236.50,59785.94
3,1003,74.15,Triple-buffered reciprocal time-frame,2016-01-10 02:31:19,0,1,29,Italy,West Terrifurt,245.89,54806.18
4,1004,68.37,Robust logistical utilization,2016-06-03 03:36:18,0,0,35,Iceland,South Manuel,225.58,73889.99

In [88]:
print('Частично пустых строк')
df_3.isna().sum()

Частично пустых строк

User_id                      0
Daily Time Spent on Site     0
Ad Topic Line                0
Timestamp                    0
Clicked on Ad                0
Male                         0
Age                          0
Country                      0
City                         0
Daily Internet Usage         0
Area Income                 50
dtype: int64

In [89]:
df_3[df_3['Area Income'].isna()].head()

,User_id,Daily Time Spent on Site,Ad Topic Line,Timestamp,Clicked on Ad,Male,Age,Country,City,Daily Internet Usage,Area Income
950,1950,63.99,Ameliorated bandwidth-monitored contingency,2016-01-11 08:18:12,1,0,43,Haiti,North Cassie,138.46,NaN
951,1951,41.35,Streamlined homogeneous analyzer,2016-03-03 03:51:27,1,1,27,Colombia,Hintonport,162.46,NaN
952,1952,62.79,Total coherent archive,2016-05-30 20:08:51,1,1,36,Luxembourg,New James,231.87,NaN
953,1953,45.53,Front-line neutral alliance,2016-04-22 22:01:21,1,0,29,United Arab Emirates,North Destiny,141.58,NaN
954,1954,51.65,Virtual context-sensitive support,2016-05-25 10:39:28,0,0,31,Ireland,Mclaughlinbury,249.99,NaN

In [90]:
df_macro[df_macro['Country'] == 'Colombia']

      Country        City  Area Income
228  Colombia  Robertbury     74430.08

In [91]:
df_4 = df_2.merge(df_macro, on=['Country', 'City'], how='inner')

print('Размер датасета df_4:', df_4.shape)
df_4.head()

Размер датасета df_4: (950, 11)

,User_id,Daily Time Spent on Site,Ad Topic Line,Timestamp,Clicked on Ad,Male,Age,Country,City,Daily Internet Usage,Area Income
0,1000,68.95,Cloned 5thgeneration orchestration,2016-03-27 00:53:11,0,0,35,Tunisia,Wrightburgh,256.09,61833.90
1,1001,80.23,Monitored national standardization,2016-04-04 01:39:02,0,1,31,Nauru,West Jodi,193.77,68441.85
2,1002,69.47,Organic bottom-line service-desk,2016-03-13 20:35:42,0,0,26,San Marino,Davidton,236.50,59785.94
3,1003,74.15,Triple-buffered reciprocal time-frame,2016-01-10 02:31:19,0,1,29,Italy,West Terrifurt,245.89,54806.18
4,1004,68.37,Robust logistical utilization,2016-06-03 03:36:18,0,0,35,Iceland,South Manuel,225.58,73889.99

In [92]:
df_5 = df_2.merge(df_macro, on=['Country', 'City'], how='right')

print('Размер датасета df_5:', df_5.shape)
df_5.head()

Размер датасета df_5: (950, 11)

,User_id,Daily Time Spent on Site,Ad Topic Line,Timestamp,Clicked on Ad,Male,Age,Country,City,Daily Internet Usage,Area Income
0,1000,68.95,Cloned 5thgeneration orchestration,2016-03-27 00:53:11,0,0,35,Tunisia,Wrightburgh,256.09,61833.90
1,1001,80.23,Monitored national standardization,2016-04-04 01:39:02,0,1,31,Nauru,West Jodi,193.77,68441.85
2,1002,69.47,Organic bottom-line service-desk,2016-03-13 20:35:42,0,0,26,San Marino,Davidton,236.50,59785.94
3,1003,74.15,Triple-buffered reciprocal time-frame,2016-01-10 02:31:19,0,1,29,Italy,West Terrifurt,245.89,54806.18
4,1004,68.37,Robust logistical utilization,2016-06-03 03:36:18,0,0,35,Iceland,South Manuel,225.58,73889.99

### join

<img src='https://statisticsglobe.com/wp-content/uploads/2021/12/join-types-python-merge-programming.png' width=700>

In [93]:
df_6 = df_site.set_index('User_id')
df_7 = df_personal.set_index('User_id')
df_6

,Daily Time Spent on Site,Ad Topic Line,Timestamp,Clicked on Ad
User_id,,,,
1000,68.95,Cloned 5thgeneration orchestration,2016-03-27 00:53:11,0
1001,80.23,Monitored national standardization,2016-04-04 01:39:02,0
1002,69.47,Organic bottom-line service-desk,2016-03-13 20:35:42,0
1003,74.15,Triple-buffered reciprocal time-frame,2016-01-10 02:31:19,0
1004,68.37,Robust logistical utilization,2016-06-03 03:36:18,0
...,...,...,...,...
1995,72.97,Fundamental modular algorithm,2016-02-11 21:49:00,1
1996,51.30,Grass-roots cohesive monitoring,2016-04-22 02:07:01,1
1997,51.63,Expanded intangible solution,2016-02-01 17:24:57,1
1998,55.55,Proactive bandwidth-monitored policy,2016-03-24 02:35:54,0
1999,45.01,Virtual 5thgeneration emulation,2016-06-03 21:43:21,1

In [94]:
df_8 = df_6.join(df_7, how='inner')

print('Размер датасета df_8:', df_8.shape)
df_8.head()

Размер датасета df_8: (1000, 9)

,Daily Time Spent on Site,Ad Topic Line,Timestamp,Clicked on Ad,Male,Age,Country,City,Daily Internet Usage
User_id,,,,,,,,,
1000,68.95,Cloned 5thgeneration orchestration,2016-03-27 00:53:11,0,0,35,Tunisia,Wrightburgh,256.09
1001,80.23,Monitored national standardization,2016-04-04 01:39:02,0,1,31,Nauru,West Jodi,193.77
1002,69.47,Organic bottom-line service-desk,2016-03-13 20:35:42,0,0,26,San Marino,Davidton,236.50
1003,74.15,Triple-buffered reciprocal time-frame,2016-01-10 02:31:19,0,1,29,Italy,West Terrifurt,245.89
1004,68.37,Robust logistical utilization,2016-06-03 03:36:18,0,0,35,Iceland,South Manuel,225.58

In [95]:
df_8 = df_8.reset_index()
df_8.head()

,User_id,Daily Time Spent on Site,Ad Topic Line,Timestamp,Clicked on Ad,Male,Age,Country,City,Daily Internet Usage
0,1000,68.95,Cloned 5thgeneration orchestration,2016-03-27 00:53:11,0,0,35,Tunisia,Wrightburgh,256.09
1,1001,80.23,Monitored national standardization,2016-04-04 01:39:02,0,1,31,Nauru,West Jodi,193.77
2,1002,69.47,Organic bottom-line service-desk,2016-03-13 20:35:42,0,0,26,San Marino,Davidton,236.50
3,1003,74.15,Triple-buffered reciprocal time-frame,2016-01-10 02:31:19,0,1,29,Italy,West Terrifurt,245.89
4,1004,68.37,Robust logistical utilization,2016-06-03 03:36:18,0,0,35,Iceland,South Manuel,225.58

## Группировки

### groupby

<img src='https://jakevdp.github.io/PythonDataScienceHandbook/figures/03.08-split-apply-combine.png'>

In [96]:
df.head()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad,User_id
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,2016-03-27 00:53:11,0,1000
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,2016-04-04 01:39:02,0,1001
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,2016-03-13 20:35:42,0,1002
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,2016-01-10 02:31:19,0,1003
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,2016-06-03 03:36:18,0,1004

In [97]:
df.groupby('Male')['Age'].mean()  # сначала берем нужную колонку, только потом агрегируем

Male
0    36.186898
1    35.817048
Name: Age, dtype: float64

In [98]:
# сначала берем нужную колонку, только потом агрегируем
df.groupby(['Male', 'Clicked on Ad'])['Daily Internet Usage'].mean()

Male  Clicked on Ad
0     0                214.623440
      1                145.539182
1     0                214.404040
      1                145.425065
Name: Daily Internet Usage, dtype: float64

In [99]:
df.groupby(['Male', 'Clicked on Ad'])['Daily Internet Usage'].mean().unstack()

Clicked on Ad          0           1
Male
0              214.62344  145.539182
1              214.40404  145.425065

In [100]:
df.groupby(['Male', 'Clicked on Ad']).agg({'Daily Internet Usage': 'mean', 'Age': ['max', 'min']})

                   Daily Internet Usage Age
                                   mean max min
Male Clicked on Ad
0    0                       214.623440  51  19
     1                       145.539182  60  19
1    0                       214.404040  53  19
     1                       145.425065  61  20

### pivot_table

In [101]:
df.pivot_table(
    index='Male',
    columns='Clicked on Ad',
    values='Daily Internet Usage',
    aggfunc='mean'
)

Clicked on Ad          0           1
Male
0              214.62344  145.539182
1              214.40404  145.425065

In [102]:
pd.pivot_table(data=df,
               values='Daily Internet Usage',
               index='Male',
               columns='Clicked on Ad',
               aggfunc='mean')

Clicked on Ad          0           1
Male
0              214.62344  145.539182
1              214.40404  145.425065

In [103]:
pd.pivot_table(data=df,
               values='Daily Internet Usage',
               index=['Male', 'Clicked on Ad'],
               columns='Country',
               aggfunc='mean')

Country             Afghanistan  Albania     Algeria  American Samoa  Andorra  \
Male Clicked on Ad
0    0                 224.2750  238.345  215.665000         209.745      NaN
     1                 134.3075  136.340  149.883333         145.925      NaN
1    0                 188.3200  193.800  178.750000             NaN      NaN
     1                 124.6100  136.520         NaN         130.410  170.205

Country             Angola    Anguilla  \
Male Clicked on Ad
0    0              251.00         NaN
     1                 NaN  195.910000
1    0              170.39  223.716667
     1              110.93  148.525000

Country             Antarctica (the territory South of 60 deg S)  \
Male Clicked on Ad
0    0                                                       NaN
     1                                                    140.46
1    0                                                    225.34
     1                                                    166.29

Country             Antigua and Barbuda  Argentina  ...  Uruguay  Uzbekistan  \
Male Clicked on Ad                                  ...
0    0                           214.42        NaN  ...  207.840      258.26
     1                           143.01        NaN  ...  255.570      225.24
1    0                              NaN     252.77  ...  211.655         NaN
     1                           160.83     110.57  ...      NaN         NaN

Country                Vanuatu  Venezuela  Vietnam  Wallis and Futuna  \
Male Clicked on Ad
0    0              235.360000   197.2925  215.040            232.285
     1                     NaN   117.6600  135.315                NaN
1    0              224.673333        NaN      NaN            225.000
     1              144.690000   134.7150      NaN            109.290

Country             Western Sahara    Yemen  Zambia    Zimbabwe
Male Clicked on Ad
0    0                  165.270000  167.260     NaN  194.620000
     1                  145.083333  125.385  135.31  144.023333
1    0                  198.100000      NaN  211.87  213.700000
     1                  143.130000      NaN  130.64  123.240000

[4 rows x 237 columns]

### pd.crosstab

In [104]:
pd.crosstab(index=df['Male'],
            columns=df['Clicked on Ad'])

Clicked on Ad    0    1
Male
0              250  269
1              250  231

In [105]:
pd.crosstab(index=df['Male'],
            columns=df['Clicked on Ad'],
            values=df['Daily Internet Usage'],
            aggfunc='mean')

Clicked on Ad          0           1
Male
0              214.62344  145.539182
1              214.40404  145.425065

In [106]:
pd.crosstab(index=df['Male'],
            columns=df['Clicked on Ad'],
            normalize='all')

Clicked on Ad     0      1
Male
0              0.25  0.269
1              0.25  0.231

In [107]:
pd.crosstab(index=df['Male'],
            columns=df['Clicked on Ad'],
            normalize='index')

Clicked on Ad         0         1
Male
0              0.481696  0.518304
1              0.519751  0.480249

In [108]:
pd.crosstab(index=df['Male'],
            columns=df['Clicked on Ad'],
            normalize='columns')

Clicked on Ad    0      1
Male
0              0.5  0.538
1              0.5  0.462

# **Дополнительные материалы**
1. Документация Pandas https://pandas.pydata.org/docs/
2. Этапы Data Science проекта - https://youtu.be/LXc6gjip_oM
2. Типы данных https://youtu.be/c4Cg3TUIH0E
2. Python for Data Analysis. Ссылка: https://github.com/wesm/pydata-book
3. Полезные методы в pandas (pd.apply, pd.replace, pd.rename, pd.set_axis): https://youtu.be/5oEh2kM9vpA
4. Полезные методы в pandas (pd.concat, pd.append, pd.merge, pd.join): https://youtu.be/9o5GQaaFxa0
5. Методы в pandas (pd.pivot_table, pd.groupby, pd.crosstab, pd.agg): https://youtu.be/uSW2pstngm0